org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=26.1.2
minecraft_version_range=[26.1, 26.2)
neo_version=26.1.2.71
neo_version_range=[26,)
loader_version_range=[4,)

mod_id=tetrachordlib
mod_name=Tetrachord Lib
mod_license=LGPL v2.1
mod_version=26.1+1.0.3
mod_group_id=com.hexagram2021.tetrachordlib
mod_authors=Liu Dongyu
mod_description=A lightweight library mod that provides various data structures such as KD Trees and Segment Trees, alongside a straightforward web socket functionality (TODO).