modLoader="javafml"
loaderVersion="[32,)"
license="LGPL v2.1"
issueTrackerURL="https://github.com/Viola-Siemens/Tetrachord-Lib/issues"

[[mods]]
modId="tetrachordlib"
version="${file.jarVersion}"
displayName="Tetrachord Lib"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
A lightweight library mod that provides various data structures such as KD Trees and Segment Trees, alongside a straightforward web socket functionality (TODO).
'''

[[dependencies.tetrachordlib]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tetrachordlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
